blank_issues_enabled: false
contact_links:
  - name: Racket Discourse - A forum for all things related to Racket. Ask your questions here!
    url: https://racket.discourse.group/tag/creative-racket
    about: Please ask and answer questions here.
  - name: Racket Discord
    url: https://discord.gg/6Zq8sH5
    about: A chat server for all things related to Racket. Ask your questions here!
  - name: Racket Slack
    url: https://racket-slack.herokuapp.com/
    about: Chat for all things related to Racket. Ask your questions here!  Click here to join.
